---
name: module3_task4
on:
  push:
    #paths:
      #- 'module3_task4/**'
    branch:
      - 'main'
    tags:
      - '1.*.*'
  schedule:
    - cron: '9 9 * * *'
jobs:
  make-help:
    runs-on: ubuntu-18.04
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: setup
        run: |
          cd module3_task4
          ./setup.sh

      - name: make build
        run: |
          cd module3_task4
          make build

      - name: make lint
        run: |
          cd module3_task4
          make lint

      - name: unit-tests
        run: |
          cd module3_task4
          make unit-tests

      - name: integration-tests
        run: |
          cd module3_task4
          make integration-tests

      - name: validate
        run: |
          cd module3_task4
          make validate

      - name: make package
        run: |
          cd module3_task4
          make package

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.*.*')
        with:
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md
          body: |
            # APLICATION'S DEPLOYMENT

            A quickstart of hugo website and how to easy set it.
            ## What is in the archive and how to unarchive it?
            you can unarchive it ...
            ## What are the commands to start and stop the application?
            you can stop it ...
            ## How to customize where the application logs are written?
            you can customize it ...
            ## How to “quickly” verify that the application is running?
            you can check ...
            ## zip
            ## tag
