---
name: module3_task0
on:
  push:
    paths:
      - 'module3_task0/**'
  schedule:
    - cron: '9 9 * * *'
jobs:
  make-help:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: help me make!
        run: |
          cd module3_task0
          make help
