---
name: module3_task2
on:
  push:
  schedule:
    - cron: '9 9 * * *'
jobs:
  make-help:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          cd module3_task1
          ./setup.sh
      - name: make build
        run: |
          cd module3_task1
          make build
      - name: make package
        run: |
          cd module3_task1
          make package
